### ISSUE TITLE
visualization tool

### ISSUE THREAD

**Issue by pipaj97** [volkamerlab/superposer#10]
We need to think of how our structures will be visualized.

**Comment by jaimergp** [comment]
Take a look at the nglview parts in this PR: https://github.com/openforcefield/openforcefield/pull/560

**Comment by jaimergp** [comment]
We can use this idiom now thanks to the new `MDAnalysis` backend:

```python
...
results = aligner([structure1, structure2])

import nglview as nv
viewer = nv.show_mdanalysis(structure1.atoms)
viewer.add_component(structure2.atoms)
viewer
```
