### ISSUE TITLE
Name of the project

### ISSUE THREAD

**Issue by pipaj97** [volkamerlab/superposer#12]
We need to think of a new name for the project because typing 'structuralalignment' is not very fun.
Jaime already suggested:
- Superposer
- Superimposer

If you have another idea, please comment it here.

**Comment by jaimergp** [comment]
Some more brainstorming:

- French would give us _superposé_, which sounds cool :)
- Spanish equivalent would be _superponer_ (infinitive), or _superpuesto_ (participle)
- Matchmaker (as in Chimera's command), but that's taken for a bunch of non-related projects!
- Aligner? Tends to be more in the sequence alignment scope though :/

**Comment by jaimergp** [comment]
More ideas:
* `alimoli`, for ALIgn MOLecules, plus an extra `i` to make it sound like `ali-oli`, the garlic-based sauce. 🧄 
* `overmol`, because it overlaps molecules. This is my favourite so far.
* `superpam`, for SUPERPose, Align and Match. 🦸‍♂️ 

Too short and probably taken:
* `sam`, for Structurally Align Molecules
* `stral`, for STRuctural ALignment? This can also become `astral` (A STRuctural ALigner), `pystral`... 🌟
* `strat`, for STRuctural Alignment Tool? The logo could be an outline for a stratocaster 🎸

**Comment by jaimergp** [comment]
More, using `sat` (Structural Alignment Tool) as the starter:

* `saturday`, `saturn`, `satellite`, `satan`, `satisfaction`... 
* `supersat`

**Comment by Tiggha** [comment]
- `saln`, for Structual ALigNment
- `ssaln`, for Superpose Structual ALigNment
- `ssa`, for Superpose Structual Alignment

**Comment by t-kimber** [comment]
Just a thought, even though French word _superposé_ sounds cool (**Not!**), I would avoid accented words.

In the same line as ``overmol``, ``supermol`` (superpose molecule).

**Comment by Tiggha** [comment]
> 
> In the same line as `overmol`, `supermol` (superpose molecule).

Alternative version for supermol: `smol`

**Comment by jaimergp** [comment]
Oh, I forgot to add this tip: we have to make sure the name of the project is not taken. This is way too common with real, cool words (like pizza) and small acronyms (sam, smol, etc).

**Comment by Tiggha** [comment]
> 
> 
> Oh, I forgot to add this tip: we have to make sure the name of the project is not taken. This is way too common with real, cool words (like pizza) and small acronyms (sam, smol, etc).

Is there a list?

**Comment by jaimergp** [comment]
You can look it up in pypi.org, but I normally Google for `python <name of project>` and see that there's no obvious matches (for example, a similarly name tool in our field would be confusing for users trying to find help on our package).

**Comment by morgeral** [comment]
I was brainstorming about a combination with strat (STRuctural Alignement Tool)
* superstrat (this is an actual term in linguistics though..) 
* overstrat
* chemstrat
* stratomol
* molestrat
Note that these names are not taken in github, but they might still have some other meanings (see google)

**Comment by jaimergp** [comment]
`superstrat` is also a type of [stratocaster ](https://en.wikipedia.org/wiki/Superstrat) (like the Ibanez JEM), which makes it even coooler!

I like `stratomol` too.

**Comment by hannahbrucemacdonald** [comment]
I think `saturn` is good if it's not already taken.

Or `eclipse` is good if this is overlaying one thing ontop of another?

Good luck picking!

**Comment by AndreaVolkamer** [comment]
Unfortunately saturn is a big shop/chain in germany :) and eclipse reminds me too much of the IDE.

**Comment by karmencj** [comment]
(py)syzygy :)

https://en.wikipedia.org/wiki/Syzygy_(astronomy)

**Comment by jaimergp** [comment]
Oh I love that one! If we call it `pysyzygy` it will be the software equivalent of Lynyrd Skynyrd, and that's not a bad thing _at all_!

... but is taken! :( https://pypi.org/project/syzygy/

**Comment by karmencj** [comment]
That's a pity!

**Comment by jaimergp** [comment]
Indeed! I was about to accept it! :(

**Comment by karmencj** [comment]
Well, keep thinking and good luck :)

**Comment by jaimergp** [comment]
I'll shortlist the suggestions so far so we can take a vote:

- `superposer`
- `overmol`
- `supermol`
- `stratomol`
- `rocknmol`, this one is new and punny! Rock-n-roll, bla bla bla. But rock can also be a verb:

![image](https://user-images.githubusercontent.com/2559438/79768087-90d58980-832a-11ea-9242-4a1ce2e081dd.png)

**Comment by AndreaVolkamer** [comment]
rocknmol is catchy :)
To all suggestions just wondering: should we have a stronger focus on proteins - which of course are also molecules - but when I use the word 'mol' then mostly in the context of small molecules.

**Comment by jaimergp** [comment]
On our last meeting, we voted we are going to rename it to `superposer`. Google ranks are not too bad and it's not taken. The change itself will take place sometime next week!

Thanks everybody for your very creative ideas!
