### ISSUE TITLE
How to get the Metadata from the atomium.model?

### ISSUE THREAD

**Issue by pipaj97** [volkamerlab/superposer#14]
How to get the Metadata from the atomium.model?

When you save the model as a pdb file, the metadata will be lost.

**Comment by jaimergp** [comment]
Which metadata are we talking about here?

Ideally, when we parse back the superposed PDB, we will only get the updated coordinates instead of the full model, but I am not sure these addresses your question :/

**Comment by pipaj97** [comment]
When you save a model as a pdb file, you will only have the atom records.

**Comment by jaimergp** [comment]
Ok, then the more reason to retrieve the coordinates from the reimported (superposed?) and update those on the initial model.
