### ISSUE TITLE
We can also try to provide the transformation matrix.

### ISSUE THREAD

**Issue by pipaj97** [volkamerlab/superposer#19]
Is there an easy way to infer that out of the delta between the original and transformed coordinates.

**Comment by jaimergp** [comment]
[This](https://www.brainvoyager.com/bv/doc/UsersGuide/CoordsAndTransforms/SpatialTransformationMatrices.html) explains how transformation matrices work.

[This project](https://github.com/matthew-brett/transforms3d) might have some algorithms already.

`scipy` has some routines ([here ](https://docs.scipy.org/doc/scipy/reference/spatial.transform.html#module-scipy.spatial.transform)and [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.affine_transform.html#scipy.ndimage.affine_transform)) and objects that could be useful:

[Some math background](https://math.stackexchange.com/questions/180418/calculate-rotation-matrix-to-align-vector-a-to-vector-b-in-3d/897677)

**Comment by jaimergp** [comment]
It might be the case that this transformation matrix is somehow already reported or, at least, calculated as part of the alignment, so maybe we can also patch the code to provide this info?
