### ISSUE TITLE
Add examples / tutorials

### ISSUE THREAD

**Issue by jaimergp** [volkamerlab/superposer#21]
Each person (@Koesed96, @Tiggha, @anniepham7) should come up with an example for their method and add that to `docs/tutorials/`. 
Each tutorial should have the following content:

* Introduction: why the chosen structures are interesting as a case study.
* Preparation: get the structures
* Alignment: use your method
* Analysis: visually inspect the superposed structures and report the RMSD, coverage, and mapped residues.

@pipaj97 will adapt this [Jupyter Notebook template](https://github.com/volkamerlab/TeachOpenCADD/blob/master/contribute/talktorial_template.ipynb) so it contains this outline and the rest will use that as a starting point. The resulting notebooks will be added to the docs using [`nbsphinx`](https://nbsphinx.readthedocs.io/en/0.6.0/). 

Check notebooks at our project [TeachOpenCADD ](https://github.com/volkamerlab/TeachOpenCADD) to see high-quality, user-ready notebooks look like ;)

**Comment by pipaj97** [comment]
I created a new PR for the template.

**Comment by pipaj97** [comment]
And maybe it is helping someone...
The NGLview only works in jupyter notebook.
I could not see the structures in vs code or jupyter lab.

**Comment by jaimergp** [comment]
Yep, for Jupyter Lab we need (yet another) plugin, because the JS backend is different. See [here](https://github.com/arose/nglview/blob/master/devtools/nglview-jupyterlab.sh) if you are curious (and disregard the strict version pinning, it should work now).

**Comment by jaimergp** [comment]
Template is now available in `master` under `docs/tutorials`! Use it for your upcoming PRs. Thanks Julian!
